name              "build-essential"
maintainer        ""
maintainer_email  ""
license           ""
description       ""
version           "0.0.1"
recipe            "build-essential", "Installs C compiler and build tools on Linux"
